export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}
           {/* Footer */}
      <footer className="text-center p-4 md:p-6 bg-slate-900 text-slate-500 border-t border-slate-800">
        © 2025 True Feedback. All rights reserved.
      </footer>
      </body>
    </html>
  )
}








